### PR TITLE
Xcode 10

### PR DESCRIPTION
**Pull request by bcylin**
Update the project to Xcode 10 and CocoaPods 1.5.3.

Also remove the version files since the swift version is specified in the project and podspec. A specific Ruby version is not necessarily required.

### CODE REVIEW

**Comment by michaljach** [comment]
Hello,
When we could see this merged ?

**Review by dlackty — APPROVED** [review]
Looks good to me. Let's merge in.

**Comment by dlackty** [comment]
@bcylin Gonna release a new version of this library, and wondering which version number we should use. #25 introduced backward incompatibilities, and thus I would prefer 2.0.0 instead of 1.6.0. What's your opinion?

**Comment by bcylin** [comment]
`2.0.0` sounds all right. 👍

**Pull request merged**
