### PR TITLE
Auto Generated Documentation

### PR DESCRIPTION
**Pull request by bcylin**
Using @polydicebot's `DANGER_GITHUB_API_TOKEN` to push updates to `gh-pages`, it'll need some help on the following setups for testing:
- [x] Add `DANGER_GITHUB_API_TOKEN` to [Travis CI env](https://travis-ci.org/polydice/ICInputAccessory/settings)
- [x] Add @polydicebot as a collaborator

### CODE REVIEW

**Comment by bcylin** [comment]
It seems that Travis CI doesn't export env variables in a PR build from a forked repo.

[PR #6](https://travis-ci.org/polydice/ICInputAccessory/builds/165270792) is missing the following setup:

```
Setting environment variables from repository settings
$ export DANGER_GITHUB_API_TOKEN=[secure]
```

but [PR #4](https://travis-ci.org/polydice/ICInputAccessory/jobs/164944827) has.

If the failure message is sent to the Slack channel, maybe `DANGER_GITHUB_API_TOKEN` can be like the Slack token, encrypted in the `.travis.yml` using the `travis` gem. Any ideas on this issue?

**Comment by dlackty** [comment]
> It seems that Travis CI doesn't export env variables in a PR build from a forked repo.

I believed that's because they don't want to expose sensitive data to 3rd party contributors. Otherwise a malicious attacker can create a pull request to just `echo` those sensitive data.

Maybe we can change documentation generation script a bit to only generate docs on `master` branch which will usually happen in original repo?

**Comment by bcylin** [comment]
Oh that makes sense. Just updated. Now it skips `danger` and `gh-pages` updates when the token is not available.

**Comment by dlackty** [comment]
Just merged in. Thanks for contribution!

**Pull request merged**
