### PR TITLE
Swift 5

### PR DESCRIPTION
**Pull request by bcylin**
Update the syntax to Swift 5 with:

- Xcode 11.1
- ~~CocoaPods 1.8.4~~

### CODE REVIEW

**Comment by dlackty** [comment]
@bcylin Could you help rebase on develop with only https://github.com/polydice/ICInputAccessory/pull/35/commits/9693dd2d6797f60783ec6004ceb723212272017f  & https://github.com/polydice/ICInputAccessory/pull/35/commits/6a7bee81e11427a0ed4b13b94e41273ded3d1764 ?

**Comment by bcylin** [comment]
Danger seems to have an unresolved issue when running on PR from a fork in GitHub Actions.

I temporarily change it to use [Danger Swift Action](https://github.com/marketplace/actions/danger-swift), which has limited features compared to Danger Ruby:

* There is no equivalent to `git.lines_of_code` in Danger Swift
* Danger Swift doesn't support `sticky:` in messages
* `git.commits` is not available in Danger Swift. I'm not sure if [`github.commits`](https://github.com/danger/swift/blob/master/Sources/Danger/GitHubDSL.swift#L21) is in the [scope of a pull request](https://github.com/danger/swift/blob/master/Sources/Danger/GitHubDSL.swift#L7)

Also, I have some problem running it locally. Overall it appears that Danger Swift is less easy to use.

There's an alternative to workaround what GitHub Actions does with a fork, but I haven't tried it yet:

```yaml
- uses: actions/checkout@v2
  with:
    fetch-depth: 0
```

Please let me know what you think.

**Comment by dlackty** [comment]
Danger.swift is quite weird.. I've tried to install using both `brew` and SPM, and still had problem running it locally.

> Danger seems to have an unresolved issue when running on PR from a fork in GitHub Actions.

Is there a link to this issue? I would prefer Danger.swift but the current state is so broken 😞

**Comment by bcylin** [comment]
I added issue #39 as this might be beyond the scope of this PR.

In the meantime, I can probably push the Swift 5 related changes to the main repo and create a different PR to work around this issue. What do you think?

**Comment by dlackty** [comment]
I added a pull request #40 which resolved the issue.

**Comment by bcylin** [comment]
Rebased the latest develop branch.

**Pull request merged**
