### PR TITLE
Swift 4.2 Support

### PR DESCRIPTION
**Pull request by michaljach**
Support for Swift 4.2

### CODE REVIEW

**Comment by bcylin** [comment]
Thanks for the pull request @michaljach. The tests should pass after #28 is merged.

**Comment by dlackty** [comment]
@michaljach Could you please rebase this branch against latest `develop` branch? I'll merge in and release a new version once CI passes.

**Comment by dlackty** [comment]
@michaljach Could you please rebase this branch against latest `develop` branch? I'll merge in and release a new version once CI passes.

**Comment by michaljach** [comment]
All done, ready to merge

**Pull request merged**
